version: '3.8'

services:
    nginx:
        build: ./nginx
        depends_on:
            - flask
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 81:81
    flask:
        build:
            context: ./server
        ports:
            - 5000:5000
        volumes:
            - ./server:/usr/src/app
    react:
        build:
            context: ./client
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/usr/src/app/src

